In [1]:
from sklearn.datasets import load_iris
import pandas as pd
from pathlib import Path

In [2]:
iris = load_iris(as_frame=True)
df = iris.frame  # feature + target 포함
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [3]:
# target을 품종명으로 바꿔보기 (연습 포인트)
df["species"] = df["target"].map(dict(enumerate(iris.target_names)))
df = df.drop(columns=["target"])
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [5]:
save_path = Path.home() / "repo/llm/data" / "iris.csv"
print(Path.home())
print(Path.cwd())
# df.to_csv("../data/iris.csv", index=False, encoding="utf-8-sig")
df.to_csv(save_path, index=False, encoding="utf-8-sig")
print("saved:", save_path)

/home/jaehyun_park
/home/jaehyun_park/repo/llm/codingtest
saved: /home/jaehyun_park/repo/llm/data/iris.csv

| 인코딩       | 설명             | 사용 상황                |
| --------- | -------------- | -------------------- |
| utf-8     | 표준 유니코드 인코딩    | 대부분의 최신 파일           |
| utf-8-sig | UTF-8 + BOM 포함 | 엑셀에서 저장한 CSV 파일      |
| cp949     | 윈도우 한글 확장 인코딩  | 오래된 한국 Windows 환경 파일 |
| euc-kr    | 구형 한글 인코딩      | 레거시 시스템 및 구형 서버      |

In [7]:
df = pd.read_csv("../data/iris.csv", encoding="utf-8-sig")
# print(df.head())
# print(df.info())

In [9]:
df = df.rename(columns={
    "sepal length (cm)": "sepal_length",
    "sepal width (cm)": "sepal_width",
    "petal length (cm)": "petal_length",
    "petal width (cm)": "petal_width",
})
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa